### ISSUE TITLE
ranseilink 5.2 crashing after going to Scenario Pokemon and Scenario Warrior tabs in succession

### ISSUE THREAD

**Issue by BagonGanda** [Deijin27/RanseiLink#20] opened 2022-12-11 00:19 UTC
me and user have encountered this error on RanseiLink 5.2- if you are to go to Scenario Pokemon, then go to the Scenario Warrior tab (or the opposite order), RanseiLink closes with a pop-up displaying this error message. 
![image](https://user-images.githubusercontent.com/84983046/206880567-b36feab6-81c1-4800-95ad-93009560ffd1.png)

**Comment by Deijin27** [comment] 2022-12-11 08:51
Closing as duplicate of #17

**Closed** 2022-12-11 08:51 UTC
